# Generated by Django 5.0.2 on 2024-03-28 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='kategoriya')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriayalar',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='ismi')),
                ('lastname', models.CharField(max_length=255, verbose_name='familyasi')),
                ('phone_number', models.CharField(max_length=255, verbose_name='telefon raqami')),
                ('email', models.CharField(max_length=255, verbose_name='elektron pochtasi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzili')),
            ],
            options={
                'verbose_name': 'Xaridor',
                'verbose_name_plural': 'Xaridorlar',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ismi')),
                ('phone_number', models.CharField(max_length=255, verbose_name='telefon raqami')),
                ('email', models.CharField(max_length=255, verbose_name='elektron pochtasi')),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('name', models.CharField(max_length=255, verbose_name='Mashina nomi')),
                ('price', models.IntegerField(verbose_name='narxi')),
                ('max_speed', models.IntegerField(verbose_name='maxsimal tezligi')),
                ('quantity', models.IntegerField(verbose_name='Soni')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='tarif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Kategoriya')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.color', verbose_name='rangi')),
            ],
            options={
                'verbose_name': 'Mashina',
                'verbose_name_plural': 'Mashinalar',
            },
        ),
    ]
